services:
  chatbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - chatbot-app:/app
      - ~/.aws:/root/.aws
    working_dir: /app

volumes:
  chatbot-app: